services:
  pg-database:
    image: postgres:latest

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi

    volumes:
      - ./nytaxi_postgres_data:/var/lib/postgresql/data:rw

    ports:
      - 5432:5432
  
  pg-admin:
    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=imrulkaish007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - 8080:80

